spring.config.import=optional:file:.env[.properties]

spring.application.name=backend



jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/quizforge_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true


# Configuración de CORS
frontend.url=${FRONTEND_URL}
